#!/bin/bash
# 
# Sets all necessary environment variables, then calls dicom2dt.pl
#
if [ ! -s testing/dicom2scalarimage_test ] ; then 
  echo please call from root Spinner directory
  exit
fi

TESTOUT=testing_output
if [ ! -s $TESTOUT ] ; then 
  mkdir  $TESTOUT
fi 

cd data
if [ ! -s sub10 ] ; then 
  unzip sub10.zip 
fi
cd ..
./src/dicom2scalarimage.sh ./data/sub10/RP1/rawdata/ 0002_t1_mpr_AX_MPRAGE  ./$TESTOUT/sub10/  sub10_RP1_t1
if [ ! -s $TESTOUT/sub10/sub10_RP1_t1.nii.gz ] ; then 
  echo $0 FAILURE --- did you set up src/dependencies.sh correctly?
  exit 1 
else 
  echo $0 SUCCESS
# now cleanup 
  rm -r ./$TESTOUT 
  exit 0
fi 
